apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  # the service must be named default
  name: default
  namespace: istio-system
spec:
  members:
    # a list of projects joined into the service mesh
    - opendatahub
