apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- workflow-crd.yaml
- argo-server-clusterolebinding.yaml
- argo-server-clusterole.yaml
- workflow-aggregate-roles.yaml
- workflow-controller-clusterrolebinding.yaml
- workflow-controller-clusterrole.yaml


configMapGenerator:
- name: argo-cluster-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: argo-cluster-parameters
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace

configurations:
- params.yaml
