
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-operators
resources:
- elasticsearch-subscription.yaml
- jaeger-subscription.yaml
- kiali-subscription.yaml
- servicemesh-subscription.yaml
